# Generated by rust2rpm 13
%bcond_without check
%global __cargo_skip_build 0

%global crate radical-native

Name:           rust-%{crate}
Version:        v0.1beta15
Release:        1%{?dist}
Summary:        Extending Riot Web with native capabilities

# Upstream license specification: MIT
License:        MIT
URL:            https://github.com/stoically/radical-native
Source:         https://codeload.github.com/proletarius101/radical-native/tar.gz/%{version}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
Requires: libsecret, sqlcipher

%global _description %{expand:
Extending Riot Web with native capabilities.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%{buildroot}%{_bindir}/radical-native
%{buildroot}%{_libdir}/mozilla/native-messaging-hosts/radical.native.json
%{buildroot}%{_docdir}/doc/radical-native/copyright

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 10 06:27:14 CST 2020 proletarius101 <proletarius101@protonmail.com> - 0.1.0~beta.15-1
- Initial package
